const PRELOAD_API_CATALOG = Object.freeze({
  getAppInfo: { kind: 'invoke' },
  getSystemAppearanceState: { kind: 'invoke' },
  consumePendingSystemOpenFiles: { kind: 'invoke' },
  onSystemOpenFileRequest: { kind: 'subscribe' },
  onAppMenuAction: { kind: 'subscribe' },
  onSystemNotificationAction: { kind: 'subscribe' },
  getDiagnosticState: { kind: 'invoke' },
  setDiagnosticLoggingEnabled: { kind: 'invoke' },
  writeDiagnosticLog: { kind: 'invoke' },
  exportDiagnosticReport: { kind: 'invoke' },
  exportDiagnosticReportAuto: { kind: 'invoke' },
  openGitHubFeedback: { kind: 'invoke' },
  getAnalysisCache: { kind: 'invoke' },
  setAnalysisCache: { kind: 'invoke' },
  deleteAnalysisCache: { kind: 'invoke' },
  clearAnalysisCache: { kind: 'invoke' },
  getAnalysisCacheState: { kind: 'invoke' },
  pruneAnalysisCache: { kind: 'invoke' },
  openExternalUrl: { kind: 'invoke' },
  showPathInFolder: { kind: 'invoke' },
  consumeCrashRecoveryState: { kind: 'invoke' },
  showSystemNotification: { kind: 'invoke' },
  setWindowProgressState: { kind: 'invoke' },
  setWindowAttentionState: { kind: 'invoke' },
  setWindowDocumentState: { kind: 'invoke' },
  getSmokeObserverState: { kind: 'invoke' },
  getPackagedSmokeConfig: { kind: 'invoke' },
  reportPackagedSmokeResult: { kind: 'invoke' },
  getAutoUpdateState: { kind: 'invoke' },
  setAutoUpdatePreferences: { kind: 'invoke' },
  checkForUpdates: { kind: 'invoke' },
  installDownloadedUpdate: { kind: 'invoke' },
  onAutoUpdateStatus: { kind: 'subscribe' },
  saveTableFile: { kind: 'invoke' },
  openQuickCorpus: { kind: 'invoke' },
  openQuickCorpusAtPath: { kind: 'invoke' },
  importAndSaveCorpus: { kind: 'invoke' },
  importCorpusPaths: { kind: 'invoke' },
  backupCorpusLibrary: { kind: 'invoke' },
  restoreCorpusLibrary: { kind: 'invoke' },
  repairCorpusLibrary: { kind: 'invoke' },
  listSavedCorpora: { kind: 'invoke' },
  listSearchableCorpora: { kind: 'invoke' },
  searchLibraryKWIC: { kind: 'invoke' },
  listRecycleBin: { kind: 'invoke' },
  restoreRecycleEntry: { kind: 'invoke' },
  purgeRecycleEntry: { kind: 'invoke' },
  createCorpusFolder: { kind: 'invoke' },
  renameCorpusFolder: { kind: 'invoke' },
  deleteCorpusFolder: { kind: 'invoke' },
  showSavedCorpusInFolder: { kind: 'invoke' },
  showRecycleEntryInFolder: { kind: 'invoke' },
  openSavedCorpus: { kind: 'invoke' },
  openSavedCorpora: { kind: 'invoke' },
  renameSavedCorpus: { kind: 'invoke' },
  moveSavedCorpus: { kind: 'invoke' },
  deleteSavedCorpus: { kind: 'invoke' },
  getSmokeAnalysisDelayMs: { kind: 'sync', fallbackValue: 0 },
  setZoomFactor: { kind: 'sync', fallbackValue: undefined },
  getZoomFactor: { kind: 'sync', fallbackValue: 1 }
})

const CRITICAL_PRELOAD_METHODS = Object.freeze([
  'getDiagnosticState',
  'exportDiagnosticReportAuto',
  'openGitHubFeedback',
  'consumeCrashRecoveryState'
])

module.exports = {
  CRITICAL_PRELOAD_METHODS,
  PRELOAD_API_CATALOG
}
