// Auto-generated by scripts/build-preload-bundle.mjs. Do not edit directly.
const { contextBridge, ipcRenderer } = require('electron')

const __WORDZ_PRELOAD_MODULES = {
  "preload/shared/logging.js": function (module, exports, require, __filename, __dirname) {
    function writePreloadLog(scope, details = null) {
      try {
        if (details && typeof details === 'object') {
          console.warn(`[startup.preload] ${scope}`, JSON.stringify(details))
          return
        }
        console.warn(`[startup.preload] ${scope}`)
      } catch {
        // ignore preload logging failures
      }
    }
    
    function writePreloadError(scope, error, details = null) {
      const normalizedError = error instanceof Error ? error : new Error(String(error || 'Unknown preload error'))
      try {
        if (details && typeof details === 'object') {
          console.error(`[startup.preload] ${scope}`, {
            message: normalizedError.message,
            stack: normalizedError.stack || '',
            ...details
          })
          return
        }
        console.error(`[startup.preload] ${scope}`, normalizedError)
      } catch {
        // ignore preload logging failures
      }
    }
    
    function deepFreeze(value, seen = new WeakSet()) {
      if (!value || typeof value !== 'object') return value
      if (seen.has(value)) return value
      seen.add(value)
      Object.freeze(value)
      for (const nestedValue of Object.values(value)) {
        deepFreeze(nestedValue, seen)
      }
      return value
    }
    
    module.exports = {
      deepFreeze,
      writePreloadError,
      writePreloadLog
    }
    
    //# sourceURL=wordz-preload://preload/shared/logging.js
  },
  "preload/shared/ipcClient.js": function (module, exports, require, __filename, __dirname) {
    const { writePreloadError } = require('./logging')
    
    function createIpcClient({ ipcRenderer, writeLog = () => {}, writeError = writePreloadError }) {
      function invoke(channel, payload) {
        if (typeof payload === 'undefined') {
          return ipcRenderer.invoke(channel)
        }
        return ipcRenderer.invoke(channel, payload)
      }
    
      function subscribe(channel, callback, scope = channel) {
        if (typeof callback !== 'function') return () => {}
        const listener = (_event, payload) => {
          try {
            callback(payload)
          } catch (error) {
            writeError('listener-failed', error, {
              channel,
              scope
            })
          }
        }
        ipcRenderer.on(channel, listener)
        writeLog('listener-ready', {
          channel,
          scope
        })
        return () => {
          ipcRenderer.removeListener(channel, listener)
        }
      }
    
      return Object.freeze({
        invoke,
        subscribe
      })
    }
    
    module.exports = {
      createIpcClient
    }
    
    //# sourceURL=wordz-preload://preload/shared/ipcClient.js
  },
  "preload/shared/guards.js": function (module, exports, require, __filename, __dirname) {
    const SAFE_ID_PATTERN = /^[A-Za-z0-9_-]{1,160}$/
    const MAX_EXPORT_ROWS = 250000
    const MAX_EXPORT_COLUMNS = 256
    const MAX_EXPORT_CELL_LENGTH = 100000
    
    function normalizeTextInput(value, maxLength) {
      return String(value ?? '').trim().slice(0, maxLength)
    }
    
    function normalizeIdentifier(value, { allowAll = false, allowEmpty = false } = {}) {
      const normalizedValue = String(value ?? '').trim()
      if (!normalizedValue) return allowEmpty ? '' : ''
      if (allowAll && normalizedValue === 'all') return 'all'
      if (!SAFE_ID_PATTERN.test(normalizedValue)) return ''
      return normalizedValue
    }
    
    function normalizeIdentifierList(values, { allowEmpty = false } = {}) {
      if (!Array.isArray(values)) return []
      const seen = new Set()
      const normalizedValues = []
    
      for (const value of values) {
        const normalizedValue = normalizeIdentifier(value, { allowEmpty })
        if (!normalizedValue || seen.has(normalizedValue)) continue
        seen.add(normalizedValue)
        normalizedValues.push(normalizedValue)
      }
    
      return normalizedValues
    }
    
    function normalizeTableRows(rows) {
      if (!Array.isArray(rows)) return []
    
      return rows.slice(0, MAX_EXPORT_ROWS).map(row => {
        if (!Array.isArray(row)) return []
        return row
          .slice(0, MAX_EXPORT_COLUMNS)
          .map(cell => String(cell ?? '').slice(0, MAX_EXPORT_CELL_LENGTH))
      })
    }
    
    function clampZoomFactor(factor) {
      const numericFactor = Number(factor)
      if (!Number.isFinite(numericFactor)) return 1
      return Math.min(Math.max(numericFactor, 0.8), 1.35)
    }
    
    function clampSmokeDelayMs(value) {
      const numericValue = Number(value)
      if (!Number.isFinite(numericValue) || numericValue <= 0) return 0
      return Math.min(Math.trunc(numericValue), 10000)
    }
    
    function normalizeBoolean(value) {
      if (typeof value === 'boolean') return value
      return ['1', 'true', 'yes', 'on'].includes(String(value ?? '').trim().toLowerCase())
    }
    
    function normalizeNotificationAction(action) {
      if (!action) return null
      if (typeof action === 'string') {
        const actionId = normalizeTextInput(action, 80)
        return actionId ? { actionId, actionPayload: null } : null
      }
      if (typeof action !== 'object') return null
      const actionId = normalizeTextInput(action.actionId ?? action.id, 80)
      if (!actionId) return null
      return {
        actionId,
        actionPayload: action.actionPayload ?? action.payload ?? null
      }
    }
    
    module.exports = {
      clampSmokeDelayMs,
      clampZoomFactor,
      normalizeBoolean,
      normalizeIdentifier,
      normalizeIdentifierList,
      normalizeNotificationAction,
      normalizeTableRows,
      normalizeTextInput
    }
    
    //# sourceURL=wordz-preload://preload/shared/guards.js
  },
  "preload/bridges/diagnosticsBridge.js": function (module, exports, require, __filename, __dirname) {
    function createDiagnosticsBridge({
      ipcClient,
      normalizeBoolean,
      normalizeTextInput
    }) {
      return {
        getDiagnosticState: () =>
          ipcClient.invoke('get-diagnostic-state'),
    
        setDiagnosticLoggingEnabled: enabled =>
          ipcClient.invoke('set-diagnostic-logging-enabled', normalizeBoolean(enabled)),
    
        writeDiagnosticLog: ({ level, scope, message, details } = {}) =>
          ipcClient.invoke('write-diagnostic-log', {
            level: normalizeTextInput(level, 16),
            scope: normalizeTextInput(scope, 80),
            message: normalizeTextInput(message, 600),
            details: details ?? null
          }),
    
        exportDiagnosticReport: rendererState =>
          ipcClient.invoke('export-diagnostic-report', rendererState ?? {}),
    
        exportDiagnosticReportAuto: rendererState =>
          ipcClient.invoke('export-diagnostic-report-auto', rendererState ?? {}),
    
        resetWindowsCompatProfile: () =>
          ipcClient.invoke('reset-windows-compat-profile'),
    
        openGitHubFeedback: ({ issueTitle, rendererState } = {}) =>
          ipcClient.invoke('open-github-feedback', {
            issueTitle: normalizeTextInput(issueTitle, 120),
            rendererState: rendererState ?? {}
          }),
    
        getAnalysisCache: cacheKey =>
          ipcClient.invoke('analysis-cache-get', {
            cacheKey: normalizeTextInput(cacheKey, 320)
          }),
    
        setAnalysisCache: (cacheKey, entry) =>
          ipcClient.invoke('analysis-cache-set', {
            cacheKey: normalizeTextInput(cacheKey, 320),
            entry: entry ?? null
          }),
    
        deleteAnalysisCache: cacheKey =>
          ipcClient.invoke('analysis-cache-delete', {
            cacheKey: normalizeTextInput(cacheKey, 320)
          }),
    
        clearAnalysisCache: () =>
          ipcClient.invoke('analysis-cache-clear'),
    
        getAnalysisCacheState: () =>
          ipcClient.invoke('analysis-cache-state'),
    
        pruneAnalysisCache: () =>
          ipcClient.invoke('analysis-cache-prune'),
    
        openExternalUrl: url =>
          ipcClient.invoke('open-external-url', normalizeTextInput(url, 4096)),
    
        showPathInFolder: targetPath =>
          ipcClient.invoke('show-path-in-folder', normalizeTextInput(targetPath, 4096)),
    
        consumeCrashRecoveryState: () =>
          ipcClient.invoke('consume-crash-recovery-state')
      }
    }
    
    module.exports = {
      createDiagnosticsBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/diagnosticsBridge.js
  },
  "preload/shared/apiCatalog.js": function (module, exports, require, __filename, __dirname) {
    const PRELOAD_API_CATALOG = Object.freeze({
      getAppInfo: { kind: 'invoke' },
      getRendererShellMarkup: { kind: 'invoke' },
      consumePendingSystemOpenFiles: { kind: 'invoke' },
      reportRendererReady: { kind: 'invoke' },
      onSystemOpenFileRequest: { kind: 'subscribe' },
      onAppMenuAction: { kind: 'subscribe' },
      onSystemNotificationAction: { kind: 'subscribe' },
      getDiagnosticState: { kind: 'invoke' },
      setDiagnosticLoggingEnabled: { kind: 'invoke' },
      writeDiagnosticLog: { kind: 'invoke' },
      exportDiagnosticReport: { kind: 'invoke' },
      exportDiagnosticReportAuto: { kind: 'invoke' },
      resetWindowsCompatProfile: { kind: 'invoke' },
      openGitHubFeedback: { kind: 'invoke' },
      getAnalysisCache: { kind: 'invoke' },
      setAnalysisCache: { kind: 'invoke' },
      deleteAnalysisCache: { kind: 'invoke' },
      clearAnalysisCache: { kind: 'invoke' },
      getAnalysisCacheState: { kind: 'invoke' },
      pruneAnalysisCache: { kind: 'invoke' },
      openExternalUrl: { kind: 'invoke' },
      showPathInFolder: { kind: 'invoke' },
      consumeCrashRecoveryState: { kind: 'invoke' },
      showSystemNotification: { kind: 'invoke' },
      setWindowProgressState: { kind: 'invoke' },
      setWindowAttentionState: { kind: 'invoke' },
      getSmokeObserverState: { kind: 'invoke' },
      getPackagedSmokeConfig: { kind: 'invoke' },
      reportPackagedSmokeResult: { kind: 'invoke' },
      getAutoUpdateState: { kind: 'invoke' },
      checkForUpdates: { kind: 'invoke' },
      installDownloadedUpdate: { kind: 'invoke' },
      onAutoUpdateStatus: { kind: 'subscribe' },
      saveTableFile: { kind: 'invoke' },
      openQuickCorpus: { kind: 'invoke' },
      openQuickCorpusAtPath: { kind: 'invoke' },
      importAndSaveCorpus: { kind: 'invoke' },
      importCorpusPaths: { kind: 'invoke' },
      backupCorpusLibrary: { kind: 'invoke' },
      restoreCorpusLibrary: { kind: 'invoke' },
      repairCorpusLibrary: { kind: 'invoke' },
      listSavedCorpora: { kind: 'invoke' },
      listSearchableCorpora: { kind: 'invoke' },
      searchLibraryKWIC: { kind: 'invoke' },
      listRecycleBin: { kind: 'invoke' },
      restoreRecycleEntry: { kind: 'invoke' },
      purgeRecycleEntry: { kind: 'invoke' },
      createCorpusFolder: { kind: 'invoke' },
      renameCorpusFolder: { kind: 'invoke' },
      deleteCorpusFolder: { kind: 'invoke' },
      showSavedCorpusInFolder: { kind: 'invoke' },
      showRecycleEntryInFolder: { kind: 'invoke' },
      openSavedCorpus: { kind: 'invoke' },
      openSavedCorpora: { kind: 'invoke' },
      renameSavedCorpus: { kind: 'invoke' },
      moveSavedCorpus: { kind: 'invoke' },
      deleteSavedCorpus: { kind: 'invoke' },
      getSmokeAnalysisDelayMs: { kind: 'sync', fallbackValue: 0 },
      setZoomFactor: { kind: 'sync', fallbackValue: undefined },
      getZoomFactor: { kind: 'sync', fallbackValue: 1 }
    })
    
    const CRITICAL_PRELOAD_METHODS = Object.freeze([
      'getDiagnosticState',
      'exportDiagnosticReportAuto',
      'openGitHubFeedback',
      'resetWindowsCompatProfile',
      'consumeCrashRecoveryState'
    ])
    
    module.exports = {
      CRITICAL_PRELOAD_METHODS,
      PRELOAD_API_CATALOG
    }
    
    //# sourceURL=wordz-preload://preload/shared/apiCatalog.js
  },
  "preload/bridges/appBridge.js": function (module, exports, require, __filename, __dirname) {
    function createAppBridge({ ipcClient }) {
      return {
        getAppInfo: () =>
          ipcClient.invoke('get-app-info'),
    
        getRendererShellMarkup: () =>
          ipcClient.invoke('get-renderer-shell-markup'),
    
        consumePendingSystemOpenFiles: () =>
          ipcClient.invoke('consume-pending-system-open-files'),
    
        reportRendererReady: (payload = {}) =>
          ipcClient.invoke('report-renderer-ready', payload),
    
        onSystemOpenFileRequest: callback =>
          ipcClient.subscribe('system-open-file-request', callback, 'onSystemOpenFileRequest'),
    
        onAppMenuAction: callback =>
          ipcClient.subscribe('app-menu-action', callback, 'onAppMenuAction'),
    
        onSystemNotificationAction: callback =>
          ipcClient.subscribe('system-notification-action', callback, 'onSystemNotificationAction')
      }
    }
    
    module.exports = {
      createAppBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/appBridge.js
  },
  "preload/bridges/libraryBridge.js": function (module, exports, require, __filename, __dirname) {
    function createLibraryBridge({
      ipcClient,
      normalizeBoolean,
      normalizeIdentifier,
      normalizeIdentifierList,
      normalizeTableRows,
      normalizeTextInput
    }) {
      return {
        saveTableFile: (defaultBaseName, rows) =>
          ipcClient.invoke('save-table-file', {
            defaultBaseName: normalizeTextInput(defaultBaseName, 120),
            rows: normalizeTableRows(rows)
          }),
    
        openQuickCorpus: () =>
          ipcClient.invoke('open-quick-corpus'),
    
        openQuickCorpusAtPath: filePath =>
          ipcClient.invoke('open-quick-corpus-at-path', normalizeTextInput(filePath, 4096)),
    
        importAndSaveCorpus: folderId =>
          ipcClient.invoke('import-and-save-corpus', {
            folderId: normalizeIdentifier(folderId, { allowEmpty: true })
          }),
    
        importCorpusPaths: (paths, { folderId = '', preserveHierarchy = true } = {}) =>
          ipcClient.invoke('import-corpus-paths', {
            paths: Array.isArray(paths)
              ? paths
                  .map(item => normalizeTextInput(item, 4096))
                  .filter(Boolean)
                  .slice(0, 500)
              : [],
            folderId: normalizeIdentifier(folderId, { allowEmpty: true }),
            preserveHierarchy: normalizeBoolean(preserveHierarchy)
          }),
    
        backupCorpusLibrary: () =>
          ipcClient.invoke('backup-corpus-library'),
    
        restoreCorpusLibrary: () =>
          ipcClient.invoke('restore-corpus-library'),
    
        repairCorpusLibrary: () =>
          ipcClient.invoke('repair-corpus-library'),
    
        listSavedCorpora: folderId =>
          ipcClient.invoke('list-saved-corpora', {
            folderId: normalizeIdentifier(folderId, { allowAll: true, allowEmpty: true })
          }),
    
        listSearchableCorpora: folderId =>
          ipcClient.invoke('list-searchable-corpora', {
            folderId: normalizeIdentifier(folderId, { allowAll: true, allowEmpty: true })
          }),
    
        searchLibraryKWIC: ({ folderId = 'all', keyword = '', leftWindowSize = 5, rightWindowSize = 5, searchOptions = {} } = {}) =>
          ipcClient.invoke('search-library-kwic', {
            folderId: normalizeIdentifier(folderId, { allowAll: true, allowEmpty: true }) || 'all',
            keyword: normalizeTextInput(keyword, 320),
            leftWindowSize: Number(leftWindowSize),
            rightWindowSize: Number(rightWindowSize),
            searchOptions: searchOptions && typeof searchOptions === 'object'
              ? {
                  words: normalizeBoolean(searchOptions.words),
                  caseSensitive: normalizeBoolean(searchOptions.caseSensitive ?? searchOptions.case),
                  regex: normalizeBoolean(searchOptions.regex)
                }
              : {}
          }),
    
        listRecycleBin: () =>
          ipcClient.invoke('list-recycle-bin'),
    
        restoreRecycleEntry: recycleEntryId =>
          ipcClient.invoke('restore-recycle-entry', normalizeIdentifier(recycleEntryId)),
    
        purgeRecycleEntry: recycleEntryId =>
          ipcClient.invoke('purge-recycle-entry', normalizeIdentifier(recycleEntryId)),
    
        createCorpusFolder: folderName =>
          ipcClient.invoke('create-corpus-folder', normalizeTextInput(folderName, 80)),
    
        renameCorpusFolder: (folderId, newName) =>
          ipcClient.invoke('rename-corpus-folder', {
            folderId: normalizeIdentifier(folderId),
            newName: normalizeTextInput(newName, 80)
          }),
    
        deleteCorpusFolder: folderId =>
          ipcClient.invoke('delete-corpus-folder', normalizeIdentifier(folderId)),
    
        showSavedCorpusInFolder: corpusId =>
          ipcClient.invoke('show-saved-corpus-in-folder', normalizeIdentifier(corpusId)),
    
        showRecycleEntryInFolder: recycleEntryId =>
          ipcClient.invoke('show-recycle-entry-in-folder', normalizeIdentifier(recycleEntryId)),
    
        openSavedCorpus: corpusId =>
          ipcClient.invoke('open-saved-corpus', normalizeIdentifier(corpusId)),
    
        openSavedCorpora: corpusIds =>
          ipcClient.invoke('open-saved-corpora', normalizeIdentifierList(corpusIds)),
    
        renameSavedCorpus: (corpusId, newName) =>
          ipcClient.invoke('rename-saved-corpus', {
            corpusId: normalizeIdentifier(corpusId),
            newName: normalizeTextInput(newName, 120)
          }),
    
        moveSavedCorpus: (corpusId, targetFolderId) =>
          ipcClient.invoke('move-saved-corpus', {
            corpusId: normalizeIdentifier(corpusId),
            targetFolderId: normalizeIdentifier(targetFolderId, { allowEmpty: true })
          }),
    
        deleteSavedCorpus: corpusId =>
          ipcClient.invoke('delete-saved-corpus', normalizeIdentifier(corpusId))
      }
    }
    
    module.exports = {
      createLibraryBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/libraryBridge.js
  },
  "preload/bridges/windowBridge.js": function (module, exports, require, __filename, __dirname) {
    function createWindowBridge({
      ipcClient,
      normalizeBoolean,
      normalizeNotificationAction,
      normalizeTextInput,
      clampZoomFactor,
      electronModuleLoader = require
    }) {
      let webFrameRef = null
    
      function getWebFrame() {
        if (webFrameRef) return webFrameRef
        const { webFrame } = electronModuleLoader('electron')
        webFrameRef = webFrame
        return webFrameRef
      }
    
      return {
        showSystemNotification: ({ title, body, subtitle, tag, silent, action } = {}) =>
          ipcClient.invoke('show-system-notification', {
            title: normalizeTextInput(title, 80),
            body: normalizeTextInput(body, 240),
            subtitle: normalizeTextInput(subtitle, 80),
            tag: normalizeTextInput(tag, 64),
            silent: normalizeBoolean(silent),
            action: normalizeNotificationAction(action)
          }),
    
        setWindowProgressState: ({ source, state, progress, priority } = {}) =>
          ipcClient.invoke('set-window-progress-state', {
            source: normalizeTextInput(source, 40),
            state: normalizeTextInput(state, 20),
            progress: Number(progress),
            priority: Number(priority)
          }),
    
        setWindowAttentionState: ({ source, state, count, description, priority, requestAttention } = {}) =>
          ipcClient.invoke('set-window-attention-state', {
            source: normalizeTextInput(source, 40),
            state: normalizeTextInput(state, 20),
            count: Number(count),
            description: normalizeTextInput(description, 120),
            priority: Number(priority),
            requestAttention: normalizeBoolean(requestAttention)
          }),
    
        setZoomFactor: factor =>
          getWebFrame().setZoomFactor(clampZoomFactor(factor)),
    
        getZoomFactor: () =>
          getWebFrame().getZoomFactor()
      }
    }
    
    module.exports = {
      createWindowBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/windowBridge.js
  },
  "preload/bridges/updateBridge.js": function (module, exports, require, __filename, __dirname) {
    function createUpdateBridge({ ipcClient }) {
      return {
        getAutoUpdateState: () =>
          ipcClient.invoke('get-auto-update-state'),
    
        checkForUpdates: () =>
          ipcClient.invoke('check-for-updates'),
    
        installDownloadedUpdate: () =>
          ipcClient.invoke('install-downloaded-update'),
    
        onAutoUpdateStatus: callback =>
          ipcClient.subscribe('auto-update-status', callback, 'onAutoUpdateStatus')
      }
    }
    
    module.exports = {
      createUpdateBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/updateBridge.js
  },
  "preload/bridges/smokeBridge.js": function (module, exports, require, __filename, __dirname) {
    function createSmokeBridge({
      ipcClient,
      clampSmokeDelayMs,
      normalizeTextInput,
      processEnv = process.env
    }) {
      return {
        getSmokeObserverState: () =>
          ipcClient.invoke('get-smoke-observer-state'),
    
        getPackagedSmokeConfig: () =>
          ipcClient.invoke('get-packaged-smoke-config'),
    
        reportPackagedSmokeResult: ({ status, stage, message, corpusName, statsRowCount, kwicResultCount, runtime } = {}) =>
          ipcClient.invoke('report-packaged-smoke-result', {
            status: normalizeTextInput(status, 24),
            stage: normalizeTextInput(stage, 80),
            message: normalizeTextInput(message, 600),
            corpusName: normalizeTextInput(corpusName, 160),
            statsRowCount: Number(statsRowCount),
            kwicResultCount: Number(kwicResultCount),
            runtime: runtime && typeof runtime === 'object'
              ? {
                  analysisMode: normalizeTextInput(runtime.analysisMode, 24),
                  searchQuery: normalizeTextInput(runtime.searchQuery, 160)
                }
              : null
          }),
    
        getSmokeAnalysisDelayMs: () =>
          clampSmokeDelayMs(processEnv.CORPUS_LITE_SMOKE_ANALYSIS_DELAY_MS)
      }
    }
    
    module.exports = {
      createSmokeBridge
    }
    
    //# sourceURL=wordz-preload://preload/bridges/smokeBridge.js
  },
  "preload/buildElectronApi.js": function (module, exports, require, __filename, __dirname) {
    const { PRELOAD_API_CATALOG, CRITICAL_PRELOAD_METHODS } = require('./shared/apiCatalog')
    const { createAppBridge } = require('./bridges/appBridge')
    const { createDiagnosticsBridge } = require('./bridges/diagnosticsBridge')
    const { createLibraryBridge } = require('./bridges/libraryBridge')
    const { createWindowBridge } = require('./bridges/windowBridge')
    const { createUpdateBridge } = require('./bridges/updateBridge')
    const { createSmokeBridge } = require('./bridges/smokeBridge')
    const { createIpcClient } = require('./shared/ipcClient')
    const guards = require('./shared/guards')
    
    const DEFAULT_BRIDGE_FACTORIES = Object.freeze([
      { name: 'appBridge', factory: createAppBridge },
      { name: 'diagnosticsBridge', factory: createDiagnosticsBridge },
      { name: 'libraryBridge', factory: createLibraryBridge },
      { name: 'windowBridge', factory: createWindowBridge },
      { name: 'updateBridge', factory: createUpdateBridge },
      { name: 'smokeBridge', factory: createSmokeBridge }
    ])
    
    function normalizeFailureError(error) {
      return error instanceof Error ? error : new Error(String(error || 'Unknown preload bridge failure'))
    }
    
    function buildFailureResult(methodName) {
      return {
        success: false,
        message: 'bridge unavailable',
        method: methodName
      }
    }
    
    function createFallbackMethod(methodName, methodConfig = {}) {
      if (methodConfig.kind === 'subscribe') {
        return () => () => {}
      }
      if (methodConfig.kind === 'sync') {
        return () => methodConfig.fallbackValue
      }
      return async () => buildFailureResult(methodName)
    }
    
    function createDegradedElectronApi({ preservedMethods = {} } = {}) {
      const electronApi = {}
      for (const [methodName, methodConfig] of Object.entries(PRELOAD_API_CATALOG)) {
        const preservedMethod = preservedMethods[methodName]
        electronApi[methodName] = typeof preservedMethod === 'function'
          ? preservedMethod
          : createFallbackMethod(methodName, methodConfig)
      }
      return electronApi
    }
    
    function pickCriticalMethods(methods = {}) {
      const criticalMethods = {}
      for (const methodName of CRITICAL_PRELOAD_METHODS) {
        if (typeof methods[methodName] === 'function') {
          criticalMethods[methodName] = methods[methodName]
        }
      }
      return criticalMethods
    }
    
    function buildElectronApi({
      ipcRenderer,
      platform = process.platform,
      sandboxed = Boolean(process.sandboxed),
      processEnv = process.env,
      electronModuleLoader = require,
      writePreloadLog = () => {},
      writePreloadError = () => {},
      bridgeFactories = DEFAULT_BRIDGE_FACTORIES
    }) {
      const preloadState = {
        platform,
        sandboxed,
        status: 'booting',
        degraded: false,
        sharedReady: false,
        bridgesReady: false,
        exposed: false,
        methodCount: 0,
        failedBridges: [],
        duplicateMethods: [],
        missingMethods: []
      }
    
      const sharedContext = {
        ipcClient: createIpcClient({
          ipcRenderer,
          writeLog: writePreloadLog,
          writeError: writePreloadError
        }),
        electronModuleLoader,
        platform,
        processEnv,
        sandboxed,
        ...guards
      }
    
      preloadState.sharedReady = true
      writePreloadLog('shared-ready', {
        platform,
        sandboxed
      })
    
      const successfulBridgeMethods = {}
      for (const bridgeEntry of bridgeFactories) {
        try {
          const bridgeMethods = bridgeEntry.factory(sharedContext)
          if (!bridgeMethods || typeof bridgeMethods !== 'object') {
            throw new Error(`bridge "${bridgeEntry.name}" did not return an object`)
          }
          for (const [methodName, methodValue] of Object.entries(bridgeMethods)) {
            if (typeof methodValue !== 'function') {
              throw new Error(`bridge "${bridgeEntry.name}" exported non-function method "${methodName}"`)
            }
            if (Object.prototype.hasOwnProperty.call(successfulBridgeMethods, methodName)) {
              preloadState.duplicateMethods.push(methodName)
              continue
            }
            successfulBridgeMethods[methodName] = methodValue
          }
        } catch (error) {
          const normalizedError = normalizeFailureError(error)
          preloadState.failedBridges.push({
            bridge: bridgeEntry.name,
            message: normalizedError.message
          })
          writePreloadError('bridge-failed', normalizedError, {
            bridge: bridgeEntry.name
          })
        }
      }
    
      preloadState.missingMethods = Object.keys(PRELOAD_API_CATALOG).filter(
        methodName => !Object.prototype.hasOwnProperty.call(successfulBridgeMethods, methodName)
      )
    
      const hasDuplicateMethods = preloadState.duplicateMethods.length > 0
      const hasBridgeFailures = preloadState.failedBridges.length > 0
      const hasMissingMethods = preloadState.missingMethods.length > 0
      preloadState.degraded = hasDuplicateMethods || hasBridgeFailures || hasMissingMethods
      preloadState.bridgesReady = true
    
      let electronApi = null
      if (hasDuplicateMethods) {
        preloadState.failedBridges.push({
          bridge: 'bridge-aggregate',
          message: `duplicate methods: ${preloadState.duplicateMethods.join(', ')}`
        })
        electronApi = createDegradedElectronApi({
          preservedMethods: pickCriticalMethods(successfulBridgeMethods)
        })
      } else if (preloadState.degraded) {
        electronApi = createDegradedElectronApi({
          preservedMethods: successfulBridgeMethods
        })
      } else {
        electronApi = successfulBridgeMethods
      }
    
      preloadState.methodCount = Object.keys(electronApi).length
      preloadState.status = preloadState.degraded ? 'degraded' : 'ready'
    
      writePreloadLog('bridges-ready', {
        methodCount: preloadState.methodCount,
        degraded: preloadState.degraded,
        failedBridges: preloadState.failedBridges,
        duplicateMethods: preloadState.duplicateMethods,
        missingMethods: preloadState.missingMethods
      })
    
      if (preloadState.degraded) {
        writePreloadLog('degraded', {
          methodCount: preloadState.methodCount,
          failedBridges: preloadState.failedBridges,
          duplicateMethods: preloadState.duplicateMethods,
          missingMethods: preloadState.missingMethods
        })
      }
    
      return {
        electronApi: Object.freeze(electronApi),
        preloadState
      }
    }
    
    module.exports = {
      buildElectronApi,
      DEFAULT_BRIDGE_FACTORIES
    }
    
    //# sourceURL=wordz-preload://preload/buildElectronApi.js
  },
  "preload/entry.js": function (module, exports, require, __filename, __dirname) {
    function fallbackWritePreloadLog(scope, details = null) {
      try {
        if (details && typeof details === 'object') {
          console.warn(`[startup.preload] ${scope}`, JSON.stringify(details))
          return
        }
        console.warn(`[startup.preload] ${scope}`)
      } catch {
        // ignore preload logging failures
      }
    }
    
    function fallbackWritePreloadError(scope, error, details = null) {
      const normalizedError = error instanceof Error ? error : new Error(String(error || 'Unknown preload error'))
      try {
        if (details && typeof details === 'object') {
          console.error(`[startup.preload] ${scope}`, {
            message: normalizedError.message,
            stack: normalizedError.stack || '',
            ...details
          })
          return
        }
        console.error(`[startup.preload] ${scope}`, normalizedError)
      } catch {
        // ignore preload logging failures
      }
    }
    
    function fallbackDeepFreeze(value, seen = new WeakSet()) {
      if (!value || typeof value !== 'object') return value
      if (seen.has(value)) return value
      seen.add(value)
      Object.freeze(value)
      for (const nestedValue of Object.values(value)) {
        fallbackDeepFreeze(nestedValue, seen)
      }
      return value
    }
    
    let writePreloadLog = fallbackWritePreloadLog
    let writePreloadError = fallbackWritePreloadError
    let deepFreeze = fallbackDeepFreeze
    
    try {
      const loggingHelpers = require('./shared/logging')
      writePreloadLog = loggingHelpers.writePreloadLog
      writePreloadError = loggingHelpers.writePreloadError
      deepFreeze = loggingHelpers.deepFreeze
    } catch (error) {
      fallbackWritePreloadError('logging-module-failed', error)
    }
    
    const EMERGENCY_SYNC_FALLBACKS = Object.freeze({
      getSmokeAnalysisDelayMs: 0,
      getZoomFactor: 1,
      setZoomFactor: undefined
    })
    
    const EMERGENCY_METHOD_NAMES = Object.freeze([
      'getAppInfo',
      'consumePendingSystemOpenFiles',
      'onSystemOpenFileRequest',
      'onAppMenuAction',
      'onSystemNotificationAction',
      'getDiagnosticState',
      'setDiagnosticLoggingEnabled',
      'writeDiagnosticLog',
      'exportDiagnosticReport',
      'exportDiagnosticReportAuto',
      'resetWindowsCompatProfile',
      'openGitHubFeedback',
      'getAnalysisCache',
      'setAnalysisCache',
      'deleteAnalysisCache',
      'clearAnalysisCache',
      'getAnalysisCacheState',
      'pruneAnalysisCache',
      'openExternalUrl',
      'showPathInFolder',
      'consumeCrashRecoveryState',
      'showSystemNotification',
      'setWindowProgressState',
      'setWindowAttentionState',
      'getSmokeObserverState',
      'getPackagedSmokeConfig',
      'reportPackagedSmokeResult',
      'getAutoUpdateState',
      'checkForUpdates',
      'installDownloadedUpdate',
      'onAutoUpdateStatus',
      'saveTableFile',
      'openQuickCorpus',
      'openQuickCorpusAtPath',
      'importAndSaveCorpus',
      'importCorpusPaths',
      'backupCorpusLibrary',
      'restoreCorpusLibrary',
      'repairCorpusLibrary',
      'listSavedCorpora',
      'listSearchableCorpora',
      'searchLibraryKWIC',
      'listRecycleBin',
      'restoreRecycleEntry',
      'purgeRecycleEntry',
      'createCorpusFolder',
      'renameCorpusFolder',
      'deleteCorpusFolder',
      'showSavedCorpusInFolder',
      'showRecycleEntryInFolder',
      'openSavedCorpus',
      'openSavedCorpora',
      'renameSavedCorpus',
      'moveSavedCorpus',
      'deleteSavedCorpus',
      'getSmokeAnalysisDelayMs',
      'setZoomFactor',
      'getZoomFactor'
    ])
    
    function createEmergencyFallbackMethod(methodName, methodConfig = null) {
      if (methodConfig?.kind === 'subscribe' || methodName.startsWith('on')) {
        return () => () => {}
      }
      if (methodConfig?.kind === 'sync' || Object.prototype.hasOwnProperty.call(EMERGENCY_SYNC_FALLBACKS, methodName)) {
        return () => EMERGENCY_SYNC_FALLBACKS[methodName]
      }
      return async () => ({
        success: false,
        message: 'bridge unavailable',
        method: methodName
      })
    }
    
    function createEmergencyPreservedMethods(ipcRenderer) {
      try {
        const { createIpcClient } = require('./shared/ipcClient')
        const guards = require('./shared/guards')
        const { createDiagnosticsBridge } = require('./bridges/diagnosticsBridge')
        const ipcClient = createIpcClient({
          ipcRenderer,
          writeLog: writePreloadLog,
          writeError: writePreloadError
        })
        return createDiagnosticsBridge({
          ipcClient,
          ...guards
        })
      } catch (error) {
        writePreloadError('emergency-diagnostics-failed', error)
        return {}
      }
    }
    
    function createEmergencyElectronApi(ipcRenderer) {
      let apiCatalog = null
      try {
        apiCatalog = require('./shared/apiCatalog').PRELOAD_API_CATALOG
      } catch (error) {
        writePreloadError('api-catalog-failed', error)
      }
    
      const preservedMethods = createEmergencyPreservedMethods(ipcRenderer)
      const methodNames = apiCatalog
        ? Object.keys(apiCatalog)
        : EMERGENCY_METHOD_NAMES
      const electronApi = {}
    
      for (const methodName of methodNames) {
        const preservedMethod = preservedMethods[methodName]
        electronApi[methodName] = typeof preservedMethod === 'function'
          ? preservedMethod
          : createEmergencyFallbackMethod(methodName, apiCatalog?.[methodName] ?? null)
      }
    
      return {
        electronApi: Object.freeze(electronApi),
        preloadState: {
          platform: process.platform,
          sandboxed: Boolean(process.sandboxed),
          status: 'degraded',
          degraded: true,
          sharedReady: false,
          bridgesReady: false,
          exposed: false,
          methodCount: Object.keys(electronApi).length,
          failedBridges: [
            {
              bridge: 'preload-entry',
              message: 'buildElectronApi failed'
            }
          ],
          duplicateMethods: [],
          missingMethods: []
        }
      }
    }
    
    function exposePreload({ contextBridge, ipcRenderer }) {
      process.once('uncaughtException', error => {
        writePreloadError('uncaughtException', error)
      })
    
      process.once('unhandledRejection', reason => {
        const normalizedError = reason instanceof Error ? reason : new Error(String(reason || 'Promise rejected'))
        writePreloadError('unhandledRejection', normalizedError)
      })
    
      writePreloadLog('begin', {
        pid: process.pid,
        platform: process.platform,
        sandboxed: Boolean(process.sandboxed)
      })
    
      let electronApi = null
      let preloadState = null
    
      try {
        const { buildElectronApi } = require('./buildElectronApi')
        const result = buildElectronApi({
          ipcRenderer,
          platform: process.platform,
          sandboxed: Boolean(process.sandboxed),
          processEnv: process.env,
          writePreloadLog,
          writePreloadError
        })
        electronApi = result.electronApi
        preloadState = result.preloadState
      } catch (error) {
        writePreloadError('build-failed', error)
        const emergencyFallback = createEmergencyElectronApi(ipcRenderer)
        electronApi = emergencyFallback.electronApi
        preloadState = emergencyFallback.preloadState
        writePreloadLog('degraded', {
          methodCount: preloadState.methodCount,
          failedBridges: preloadState.failedBridges
        })
      }
    
      try {
        preloadState.exposed = true
        const exposedState = deepFreeze({
          ...preloadState
        })
        contextBridge.exposeInMainWorld('electronAPI', electronApi)
        contextBridge.exposeInMainWorld('__WORDZ_PRELOAD_STATE__', exposedState)
        writePreloadLog('exposed', {
          methodCount: preloadState.methodCount,
          degraded: preloadState.degraded,
          status: preloadState.status
        })
      } catch (error) {
        writePreloadError('expose-failed', error, {
          methodCount: preloadState?.methodCount || 0,
          degraded: preloadState?.degraded ?? true
        })
        throw error
      }
    }
    
    module.exports = {
      exposePreload
    }
    
    //# sourceURL=wordz-preload://preload/entry.js
  }
}

const __WORDZ_PRELOAD_CACHE = Object.create(null)

function __normalizePreloadBundlePath(value) {
  const parts = []
  for (const part of String(value || '').split('/')) {
    if (!part || part === '.') continue
    if (part === '..') {
      parts.pop()
      continue
    }
    parts.push(part)
  }
  return parts.join('/')
}

function __resolvePreloadBundleRequest(fromId, request) {
  if (!request.startsWith('./') && !request.startsWith('../')) return request
  const parentParts = fromId.split('/')
  parentParts.pop()
  return __normalizePreloadBundlePath(parentParts.concat(request.split('/')).join('/')) + '.js'
}

function __loadPreloadBundleModule(moduleId) {
  if (__WORDZ_PRELOAD_CACHE[moduleId]) {
    return __WORDZ_PRELOAD_CACHE[moduleId].exports
  }

  const factory = __WORDZ_PRELOAD_MODULES[moduleId]
  if (typeof factory !== 'function') {
    throw new Error(`module not found: ${moduleId}`)
  }

  const module = { exports: {} }
  __WORDZ_PRELOAD_CACHE[moduleId] = module
  const dirnameParts = moduleId.split('/')
  dirnameParts.pop()
  const dirname = dirnameParts.join('/') || '.'
  factory(module, module.exports, __createPreloadBundleRequire(moduleId), moduleId, dirname)
  return module.exports
}

function __createPreloadBundleRequire(fromId) {
  return function preloadBundleRequire(request) {
    const resolvedRequest = __resolvePreloadBundleRequest(fromId, request)
    if (resolvedRequest === request) {
      return require(request)
    }
    return __loadPreloadBundleModule(resolvedRequest)
  }
}

const __wordzPreloadEntry = __loadPreloadBundleModule("preload/entry.js")
__wordzPreloadEntry.exposePreload({ contextBridge, ipcRenderer })
