import Foundation

extension WorkspacePersistenceService {
    func buildDraft(
        selectedTab: WorkspaceDetailTab,
        selectedFolderID: String = "all",
        selectedCorpusSetID: String = "",
        selectedCorpus: LibraryCorpusItem?,
        openedCorpus: OpenedCorpus?,
        searchQuery: String,
        searchOptions: SearchOptionsState,
        stopwordFilter: StopwordFilterState,
        tokenizeLanguagePreset: TokenizeLanguagePreset = .mixedChineseEnglish,
        tokenizeLemmaStrategy: TokenLemmaStrategy = .normalizedSurface,
        compareReferenceCorpusID: String = "",
        compareSelectedCorpusIDs: [String] = [],
        keywordTargetCorpusID: String = "",
        keywordReferenceCorpusID: String = "",
        keywordLowercased: Bool = true,
        keywordRemovePunctuation: Bool = true,
        keywordMinimumFrequency: String = "2",
        keywordStatistic: KeywordStatisticMethod = .logLikelihood,
        keywordStopwordFilter: StopwordFilterState = .default,
        ngramSize: String,
        ngramPageSize: String,
        kwicLeftWindow: String,
        kwicRightWindow: String,
        collocateLeftWindow: String,
        collocateRightWindow: String,
        collocateMinFreq: String,
        topicsMinTopicSize: String,
        topicsIncludeOutliers: Bool,
        topicsPageSize: String,
        topicsActiveTopicID: String,
        frequencyNormalizationUnit: FrequencyNormalizationUnit = FrequencyMetricDefinition.default.normalizationUnit,
        frequencyRangeMode: FrequencyRangeMode = FrequencyMetricDefinition.default.rangeMode,
        chiSquareA: String,
        chiSquareB: String,
        chiSquareC: String,
        chiSquareD: String,
        chiSquareUseYates: Bool
    ) -> WorkspaceStateDraft {
        let selectedCorpusState = selectedCorpusState(selectedCorpus: selectedCorpus, openedCorpus: openedCorpus)

        return WorkspaceStateDraft(
            currentTab: selectedTab.snapshotValue,
            currentLibraryFolderId: selectedFolderID,
            selectedCorpusSetID: selectedCorpusSetID,
            corpusIds: selectedCorpusState.ids,
            corpusNames: selectedCorpusState.names,
            searchQuery: searchQuery,
            searchOptions: searchOptions,
            stopwordFilter: stopwordFilter,
            tokenizeLanguagePreset: tokenizeLanguagePreset,
            tokenizeLemmaStrategy: tokenizeLemmaStrategy,
            compareReferenceCorpusID: compareReferenceCorpusID,
            compareSelectedCorpusIDs: compareSelectedCorpusIDs,
            keywordTargetCorpusID: keywordTargetCorpusID,
            keywordReferenceCorpusID: keywordReferenceCorpusID,
            keywordLowercased: keywordLowercased,
            keywordRemovePunctuation: keywordRemovePunctuation,
            keywordMinimumFrequency: keywordMinimumFrequency,
            keywordStatistic: keywordStatistic,
            keywordStopwordFilter: keywordStopwordFilter,
            ngramSize: ngramSize,
            ngramPageSize: ngramPageSize,
            kwicLeftWindow: kwicLeftWindow,
            kwicRightWindow: kwicRightWindow,
            collocateLeftWindow: collocateLeftWindow,
            collocateRightWindow: collocateRightWindow,
            collocateMinFreq: collocateMinFreq,
            topicsMinTopicSize: topicsMinTopicSize,
            topicsIncludeOutliers: topicsIncludeOutliers,
            topicsPageSize: topicsPageSize,
            topicsActiveTopicID: topicsActiveTopicID,
            frequencyNormalizationUnit: frequencyNormalizationUnit,
            frequencyRangeMode: frequencyRangeMode,
            chiSquareA: chiSquareA,
            chiSquareB: chiSquareB,
            chiSquareC: chiSquareC,
            chiSquareD: chiSquareD,
            chiSquareUseYates: chiSquareUseYates
        )
    }
}
