import Foundation

extension WorkspacePersistenceService {
    func buildDraft(
        selectedTab: WorkspaceDetailTab,
        selectedFolderID: String = "all",
        selectedCorpusSetID: String = "",
        selectedCorpus: LibraryCorpusItem?,
        openedCorpus: OpenedCorpus?,
        searchQuery: String,
        searchOptions: SearchOptionsState,
        stopwordFilter: StopwordFilterState,
        tokenizeLanguagePreset: TokenizeLanguagePreset = .mixedChineseEnglish,
        tokenizeLemmaStrategy: TokenLemmaStrategy = .normalizedSurface,
        compareReferenceCorpusID: String = "",
        compareSelectedCorpusIDs: [String] = [],
        sentimentSource: SentimentInputSource = .openedCorpus,
        sentimentUnit: SentimentAnalysisUnit = .sentence,
        sentimentContextBasis: SentimentContextBasis = .visibleContext,
        sentimentBackend: SentimentBackendKind = .lexicon,
        sentimentChartKind: SentimentChartKind = .distributionBar,
        sentimentThresholdPreset: SentimentThresholdPreset = .conservative,
        sentimentDecisionThreshold: Double = SentimentThresholds.default.decisionThreshold,
        sentimentMinimumEvidence: Double = SentimentThresholds.default.minimumEvidence,
        sentimentNeutralBias: Double = SentimentThresholds.default.neutralBias,
        sentimentRowFilterQuery: String = "",
        sentimentLabelFilter: SentimentLabel? = nil,
        sentimentSelectedCorpusIDs: [String] = [],
        sentimentReferenceCorpusID: String = "",
        keywordActiveTab: KeywordSuiteTab = .words,
        keywordSuiteConfiguration: KeywordSuiteConfiguration = .default,
        keywordTargetCorpusID: String = "",
        keywordReferenceCorpusID: String = "",
        keywordLowercased: Bool = true,
        keywordRemovePunctuation: Bool = true,
        keywordMinimumFrequency: String = "2",
        keywordStatistic: KeywordStatisticMethod = .logLikelihood,
        keywordStopwordFilter: StopwordFilterState = .default,
        plotQuery: String = "",
        plotSearchOptions: SearchOptionsState = .default,
        ngramSize: String,
        ngramPageSize: String,
        clusterSelectedN: String = "3",
        clusterMinFrequency: String = "3",
        clusterSortMode: ClusterSortMode = .frequencyDescending,
        clusterCaseSensitive: Bool = false,
        clusterStopwordFilter: StopwordFilterState = .default,
        clusterPunctuationMode: ClusterPunctuationMode = .boundary,
        clusterSelectedPhrase: String = "",
        clusterPageSize: String = "100",
        clusterReferenceCorpusID: String = "",
        kwicLeftWindow: String,
        kwicRightWindow: String,
        collocateLeftWindow: String,
        collocateRightWindow: String,
        collocateMinFreq: String,
        topicsMinTopicSize: String,
        topicsKeywordDisplayCount: String = "5",
        topicsIncludeOutliers: Bool,
        topicsPageSize: String,
        topicsActiveTopicID: String,
        frequencyNormalizationUnit: FrequencyNormalizationUnit = FrequencyMetricDefinition.default.normalizationUnit,
        frequencyRangeMode: FrequencyRangeMode = FrequencyMetricDefinition.default.rangeMode,
        chiSquareA: String,
        chiSquareB: String,
        chiSquareC: String,
        chiSquareD: String,
        chiSquareUseYates: Bool
    ) -> WorkspaceStateDraft {
        let selectedCorpusState = selectedCorpusState(selectedCorpus: selectedCorpus, openedCorpus: openedCorpus)

        return WorkspaceStateDraft(
            currentTab: selectedTab.snapshotValue,
            currentLibraryFolderId: selectedFolderID,
            selectedCorpusSetID: selectedCorpusSetID,
            corpusIds: selectedCorpusState.ids,
            corpusNames: selectedCorpusState.names,
            searchQuery: searchQuery,
            searchOptions: searchOptions,
            stopwordFilter: stopwordFilter,
            tokenizeLanguagePreset: tokenizeLanguagePreset,
            tokenizeLemmaStrategy: tokenizeLemmaStrategy,
            compareReferenceCorpusID: compareReferenceCorpusID,
            compareSelectedCorpusIDs: compareSelectedCorpusIDs,
            sentimentSource: sentimentSource,
            sentimentUnit: sentimentUnit,
            sentimentContextBasis: sentimentContextBasis,
            sentimentBackend: sentimentBackend,
            sentimentChartKind: sentimentChartKind,
            sentimentThresholdPreset: sentimentThresholdPreset,
            sentimentDecisionThreshold: sentimentDecisionThreshold,
            sentimentMinimumEvidence: sentimentMinimumEvidence,
            sentimentNeutralBias: sentimentNeutralBias,
            sentimentRowFilterQuery: sentimentRowFilterQuery,
            sentimentLabelFilter: sentimentLabelFilter,
            sentimentSelectedCorpusIDs: sentimentSelectedCorpusIDs,
            sentimentReferenceCorpusID: sentimentReferenceCorpusID,
            keywordActiveTab: keywordActiveTab,
            keywordSuiteConfiguration: keywordSuiteConfiguration,
            keywordTargetCorpusID: keywordTargetCorpusID,
            keywordReferenceCorpusID: keywordReferenceCorpusID,
            keywordLowercased: keywordLowercased,
            keywordRemovePunctuation: keywordRemovePunctuation,
            keywordMinimumFrequency: keywordMinimumFrequency,
            keywordStatistic: keywordStatistic,
            keywordStopwordFilter: keywordStopwordFilter,
            plotQuery: plotQuery,
            plotSearchOptions: plotSearchOptions,
            ngramSize: ngramSize,
            ngramPageSize: ngramPageSize,
            clusterSelectedN: clusterSelectedN,
            clusterMinFrequency: clusterMinFrequency,
            clusterSortMode: clusterSortMode,
            clusterCaseSensitive: clusterCaseSensitive,
            clusterStopwordFilter: clusterStopwordFilter,
            clusterPunctuationMode: clusterPunctuationMode,
            clusterSelectedPhrase: clusterSelectedPhrase,
            clusterPageSize: clusterPageSize,
            clusterReferenceCorpusID: clusterReferenceCorpusID,
            kwicLeftWindow: kwicLeftWindow,
            kwicRightWindow: kwicRightWindow,
            collocateLeftWindow: collocateLeftWindow,
            collocateRightWindow: collocateRightWindow,
            collocateMinFreq: collocateMinFreq,
            topicsMinTopicSize: topicsMinTopicSize,
            topicsKeywordDisplayCount: topicsKeywordDisplayCount,
            topicsIncludeOutliers: topicsIncludeOutliers,
            topicsPageSize: topicsPageSize,
            topicsActiveTopicID: topicsActiveTopicID,
            frequencyNormalizationUnit: frequencyNormalizationUnit,
            frequencyRangeMode: frequencyRangeMode,
            chiSquareA: chiSquareA,
            chiSquareB: chiSquareB,
            chiSquareC: chiSquareC,
            chiSquareD: chiSquareD,
            chiSquareUseYates: chiSquareUseYates
        )
    }
}
